
version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
  streamlit:
    image: streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app/streamlit_app
    command: streamlit run app.py
